version: '3.8'

services:
  app-7:
    build: .
    ports:
      - "3007:3000"
    environment:
      - NODE_ENV=production
      - DEPLOYMENT_ID=7
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3